# Generated by Django 3.0.3 on 2020-03-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_point_de_retrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGENT_DESTINY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomA', models.CharField(max_length=100)),
                ('prenomA', models.CharField(max_length=100)),
                ('dateNaissA', models.DateField()),
                ('emailA', models.EmailField(max_length=254)),
                ('sexeA', models.CharField(choices=[('M', 'Masculin'), ('N', 'Feminin')], default='M', max_length=1)),
                ('adresseA', models.CharField(max_length=100)),
                ('villeA', models.CharField(max_length=100)),
                ('quartierA', models.CharField(max_length=100)),
                ('numCNI_A', models.CharField(max_length=25, unique=True)),
                ('telA', models.IntegerField()),
                ('loginA', models.CharField(max_length=100)),
                ('motDePassA', models.CharField(max_length=50)),
            ],
        ),
    ]
