# Generated by Django 3.0.3 on 2020-03-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_agent_destiny'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomC', models.CharField(max_length=100)),
                ('prenomC', models.CharField(max_length=100)),
                ('dateNaissC', models.DateField()),
                ('emailC', models.EmailField(max_length=254)),
                ('sexeC', models.CharField(choices=[('M', 'Masculin'), ('N', 'Feminin')], default='M', max_length=1)),
                ('adresseC', models.CharField(max_length=100)),
                ('villeC', models.CharField(max_length=100)),
                ('quartierC', models.CharField(max_length=100)),
                ('numCNI_C', models.CharField(max_length=25, unique=True)),
                ('telC', models.IntegerField()),
                ('loginC', models.CharField(max_length=100)),
                ('motDePassC', models.CharField(max_length=100)),
            ],
        ),
    ]
