# Generated by Django 3.0.3 on 2020-03-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='LIVREUR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomL', models.CharField(max_length=100)),
                ('prenomL', models.CharField(max_length=100)),
                ('dateNaissL', models.DateField()),
                ('emailL', models.EmailField(max_length=254)),
                ('sexeL', models.CharField(choices=[('M', 'Masculin'), ('N', 'Feminin')], default='M', max_length=1)),
                ('adresseL', models.CharField(max_length=100)),
                ('villeL', models.CharField(max_length=100)),
                ('quartierL', models.CharField(max_length=100)),
                ('numCNI_L', models.CharField(max_length=100, unique=True)),
                ('telL', models.IntegerField()),
                ('loginL', models.CharField(max_length=100)),
                ('motDePassL', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='motDePassC',
            field=models.CharField(max_length=50),
        ),
    ]
