# Generated by Django 3.0.3 on 2020-03-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200329_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_destiny',
            name='sexeA',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='sexeC',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='sexeL',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=1),
        ),
    ]
