# Generated by Django 3.0.3 on 2020-03-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200329_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_destiny',
            name='emailA',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='emailC',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='emailL',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='point_de_retrait',
            name='mailPoint',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='emailP',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
