# Generated by Django 3.0.3 on 2020-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_marque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='photoMarq',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
