# Generated by Django 3.0.3 on 2020-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200329_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORIE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libCat', models.CharField(max_length=50)),
                ('photoCat', models.CharField(max_length=256)),
            ],
        ),
    ]
