# Generated by Django 3.0.3 on 2020-03-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200329_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOUS_CATEGORIE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libSCat', models.CharField(max_length=50)),
                ('photoSCat', models.CharField(max_length=256)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CATEGORIE')),
            ],
        ),
    ]
