# Generated by Django 3.0.3 on 2020-03-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200329_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent_destiny',
            options={'ordering': ['nomA']},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['libCat']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nomC']},
        ),
        migrations.AlterModelOptions(
            name='livreur',
            options={'ordering': ['nomL']},
        ),
        migrations.AlterModelOptions(
            name='marque',
            options={'ordering': ['libMarq']},
        ),
        migrations.AlterModelOptions(
            name='point_de_retrait',
            options={'ordering': ['libPoint']},
        ),
        migrations.AlterModelOptions(
            name='prestataire',
            options={'ordering': ['nomP']},
        ),
        migrations.AlterModelOptions(
            name='sous_categorie',
            options={'ordering': ['libSCat']},
        ),
        migrations.CreateModel(
            name='PANIER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libPanier', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CLIENT')),
            ],
            options={
                'ordering': ['libPanier'],
            },
        ),
    ]
