# Generated by Django 3.0.3 on 2020-03-29 19:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20200329_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVENEMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libEven', models.CharField(max_length=100)),
                ('dateEven', models.DateTimeField(default=django.utils.timezone.now)),
                ('descriptionEven', models.CharField(max_length=256)),
                ('agent_destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.AGENT_DESTINY')),
            ],
            options={
                'ordering': ['libEven'],
            },
        ),
    ]
