# Generated by Django 3.0.3 on 2020-03-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='RETOUR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motifRetour', models.CharField(max_length=100)),
                ('dateRetour', models.DateField()),
                ('statutRetour', models.CharField(choices=[('EA', 'En Attente'), ('A', 'APPROUVÉ'), ('R', 'REFUSEÉ'), ('EX', "En cour d'éxécution"), ('V', 'Validé')], default='EA', max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CLIENT')),
            ],
        ),
    ]
