# Generated by Django 3.0.3 on 2020-03-29 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_retour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retour',
            options={'ordering': ['motifRetour']},
        ),
        migrations.AlterField(
            model_name='retour',
            name='statutRetour',
            field=models.CharField(choices=[('EA', 'En Attente'), ('A', 'Approuvé'), ('R', 'Refusé'), ('EX', "En cour d'éxécution"), ('V', 'Validé')], default='EA', max_length=2),
        ),
        migrations.CreateModel(
            name='COMMANDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libCmd', models.CharField(max_length=100)),
                ('dateCmd', models.DateField()),
                ('statusCmd', models.CharField(choices=[('EA', 'En Attente'), ('L', 'Livré'), ('AR', 'A Rétirer'), ('EL', 'En cour de livraison'), ('R', 'reçu')], default='EA', max_length=2)),
                ('descriptionCmd', models.CharField(max_length=256)),
                ('montantLivraisonCmd', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CLIENT')),
            ],
        ),
    ]
