# Generated by Django 3.0.3 on 2020-03-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20200329_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['libCmd']},
        ),
    ]
