# Generated by Django 3.0.3 on 2020-03-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20200329_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['designationAr']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='reporter',
        ),
        migrations.AddField(
            model_name='article',
            name='StockSecuriteAr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='VideoPubAr',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='article',
            name='designationAr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='marque',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.MARQUE'),
        ),
        migrations.AddField(
            model_name='article',
            name='nbAchatAr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='panier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.PANIER'),
        ),
        migrations.AddField(
            model_name='article',
            name='photoAr',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='article',
            name='prixAr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='qteAr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='sous_categorie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.SOUS_CATEGORIE'),
        ),
        migrations.AddField(
            model_name='commande',
            name='articles',
            field=models.ManyToManyField(to='store.ARTICLE'),
        ),
    ]
