# Generated by Django 3.0.3 on 2020-03-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20200330_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='panier',
        ),
        migrations.AlterField(
            model_name='commande',
            name='articles',
            field=models.ManyToManyField(to='store.ARTICLE'),
        ),
    ]
