# Generated by Django 3.0.3 on 2020-03-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20200330_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='articles',
            field=models.ManyToManyField(to='store.ARTICLE'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='articles',
            field=models.ManyToManyField(to='store.ARTICLE'),
        ),
        migrations.CreateModel(
            name='CARACTERISTIQUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleurCaract', models.CharField(max_length=100)),
                ('photoCaract', models.CharField(blank=True, max_length=256, null=True)),
                ('tailleCaract', models.IntegerField()),
                ('autreDetailCaract', models.CharField(max_length=256)),
                ('prixCaract', models.IntegerField()),
                ('qteCaract', models.IntegerField()),
                ('nbAchatCaract', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ARTICLE')),
            ],
        ),
    ]
