# Generated by Django 3.0.3 on 2020-03-30 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20200330_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristique',
            options={'ordering': ['article']},
        ),
        migrations.AlterField(
            model_name='caracteristique',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ARTICLE'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='articles',
            field=models.ManyToManyField(to='store.ARTICLE'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='articles',
            field=models.ManyToManyField(to='store.ARTICLE'),
        ),
        migrations.CreateModel(
            name='DETAIL_COMMANDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_Commander', models.IntegerField()),
                ('caracteristique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CARACTERISTIQUE')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.COMMANDE')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='caracteristiques',
            field=models.ManyToManyField(through='store.DETAIL_COMMANDE', to='store.CARACTERISTIQUE'),
        ),
    ]
