# Generated by Django 3.0.3 on 2020-03-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200324_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='autor',
        ),
    ]
