# Generated by Django 3.0.3 on 2020-03-24 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_movie_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Person'),
        ),
    ]
